repo:
  - any: ["./*"]

actions:
  - any: [".github/**"]

docs:
  - any: ["docs/**/*"]

lambda:
  - any: ["lambda_functions/**/*"]

infrastructure:
  - any: ["terraform/**/*"]

scripts:
  - any: ["scripts/**/*"]
