---
- repo: git://github.com/p1c2u/openapi-spec-validator
  rev: master
  hooks:
  - id: openapi-spec-validator
    name: openapi-spec-validator
    entry: openapi-spec-validator
    description: Hook to validate Open API specs.
    language: python
    files: .*openapi.*\.(json|yaml|yml)
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.17.0
  hooks:
    - id: yamllint
      args: [-c=./.yamllint]
