---


- repo: https://github.com/p1c2u/openapi-spec-validator
  rev: 0.4.0
  hooks:
  - id: openapi-spec-validator
    name: openapi-spec-validator
    entry: openapi-spec-validator
    description: Hook to validate Open API specs.
    language: python
    files: .*lpa-codes-openapi.*\.(json|yaml|yml)
#- repo: https://github.com/adrienverge/yamllint.git
#  rev: v1.17.0
#  hooks:
#    - id: yamllint
#      args: [-c=./.yamllint]
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.19.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: detect-private-key
    - id: flake8
      args: ['--ignore=W503', '--exclude=docs/supportscripts/*']
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
