---
repos:
  - repo: https://github.com/python-openapi/openapi-spec-validator
    rev:  0.7.1
    hooks:
    - id: openapi-spec-validator
      name: openapi-spec-validator
      entry: openapi-spec-validator
      description: Hook to validate Open API specs.
      language: python
      files: .*lpa-codes-openapi.*\.(json|yaml|yml)
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=./.yamllint]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: flake8
        args: ['--ignore=W503', '--exclude=docs/supportscripts/*']
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
