vulnerabilities:
  - id: CVE-2025-11563
    statement: Waiting for lambda/provided image update
    expired_at: 2025-12-20
  - id: CVE-2025-13601
    statement: Waiting for lambda/provided image update
    expired_at: 2025-12-20
