vulnerabilities:
  - id: CVE-2026-24882
    statement: Waiting for lambda/provided image update
    expired_at: 2026-03-02
  - id: CVE-2025-15468
    statement: Waiting for lambda/provided image update
    expired_at: 2026-03-02
  - id: CVE-2025-66199
    statement: Waiting for lambda/provided image update
    expired_at: 2026-03-02
  - id: CVE-2025-68160
    statement: Waiting for lambda/provided image update
    expired_at: 2026-03-02
  - id: CVE-2025-69418
    statement: Waiting for lambda/provided image update
    expired_at: 2026-03-02
  - id: CVE-2025-69419
    statement: Waiting for lambda/provided image update
    expired_at: 2026-03-02
  - id: CVE-2025-69420
    statement: Waiting for lambda/provided image update
    expired_at: 2026-03-02
  - id: CVE-2025-69421
    statement: Waiting for lambda/provided image update
    expired_at: 2026-03-02
  - id: CVE-2026-22795
    statement: Waiting for lambda/provided image update
    expired_at: 2026-03-02
  - id: CVE-2026-22796
    statement: Waiting for lambda/provided image update
    expired_at: 2026-03-02
