vulnerabilities:
  - id: CVE-2025-8732
    statement: Waiting for lambda/provided image update
    expired_at: 2026-02-20
  - id: CVE-2025-68973
    statement: Deferring for a week
    expired_at: 2026-02-20
  - id: CVE-2025-61726
    statement: Deferring for a week
    expired_at: 2026-02-20
  - id: CVE-2025-61728
    statement: Deferring for a week
    expired_at: 2026-02-20
  - id: CVE-2025-61730
    statement: Deferring for a week
    expired_at: 2026-02-20
  - id: CVE-2025-61731
    statement: Deferring for a week
    expired_at: 2026-02-20
  - id: CVE-2025-68119
    statement: Deferring for a week
    expired_at: 2026-02-20
  - id: CVE-2025-68121
    statement: Deferring for a week
    expired_at: 2026-02-20
  - id: CVE-2025-13151
    statement: Deferring for a week
    expired_at: 2026-02-20
  - id: CVE-2025-15467
    statement: Deferring for a week
    expired_at: 2026-02-20
  - id: CVE-2025-68121
    statement: Deferring for a week
    expired_at: 2026-02-20
