vulnerabilities:
  - id: CVE-2025-47912
    statement: Waiting for lambda/provided image update
    expired_at: 2025-11-10
  - id: CVE-2025-58183
    statement: Waiting for lambda/provided image update
    expired_at: 2025-11-10
  - id: CVE-2025-58185
    statement: Waiting for lambda/provided image update
    expired_at: 2025-11-10
  - id: CVE-2025-58186
    statement: Waiting for lambda/provided image update
    expired_at: 2025-11-10
  - id: CVE-2025-58187
    statement: Waiting for lambda/provided image update
    expired_at: 2025-11-10
  - id: CVE-2025-58188
    statement: Waiting for lambda/provided image update
    expired_at: 2025-11-10
  - id: CVE-2025-58189
    statement: Waiting for lambda/provided image update
    expired_at: 2025-11-10
  - id: CVE-2025-61723
    statement: Waiting for lambda/provided image update
    expired_at: 2025-11-10
  - id: CVE-2025-61724
    statement: Waiting for lambda/provided image update
    expired_at: 2025-11-10
  - id: CVE-2025-61725
    statement: Waiting for lambda/provided image update
    expired_at: 2025-11-10
