services:
  postgres:
    image: postgres@sha256:29e0bb09c8e7e7fc265ea9f4367de9622e55bae6b0b97e7cce740c2d63c2ebc0
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password #pragma: allowlist secret
      POSTGRES_DB: postgres
  broker_app:
    image: pactfoundation/pact-broker@sha256:05b05a192c771b33ba67ffdf2d6829bb32600145ca8f154165187d318c8ee70f
    ports:
      - "9293:80"
      - "9292:9292"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password #pragma: allowlist secret
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      #Uncomment these two options for debugging purposes:
      # PACT_BROKER_WEBHOOK_HOST_WHITELIST: circleci.com
      # PACT_BROKER_LOG_LEVEL: DEBUG
  api_gateway:
    build:
      dockerfile: Dockerfile-Local-Helper
      context: ./lambda_functions/v1
    ports:
      - "4343:4343"
    volumes:
      - ./lambda_functions/v1/:/var/www/lambda_functions/v1/
    depends_on:
      - dynamodb
    environment:
      LOCAL_URL: http://dynamodb:8000
      ENVIRONMENT: local
      AWS_ACCESS_KEY_ID: testing
      AWS_SECRET_ACCESS_KEY: testing #pragma: allowlist secret
      AWS_SECURITY_TOKEN: testing
      AWS_SESSION_TOKEN: testing
      AWS_DEFAULT_REGION: eu-west-1
    networks:
      default:
        aliases:
          - lpa-codes.local
  dynamodb:
    image: amazon/dynamodb-local:latest@sha256:2fed5e3a965a4ba5aa6ac82baec57058b5a3848e959d705518f3fd579a77e76b
    entrypoint: java
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - lpa-codes.local
  pact-verifier:
    image: pactfoundation/pact-ref-verifier@sha256:514b680cd0ad2fa95c6df7a541e3b03c8dd1176de26e84e58a349de96e305bce
    entrypoint:
      - pact_verifier_cli
      - --hostname=api_gateway
      - --port=4343
      - --base-path=/v1/
      - "--header=Authorization=asdf1234567890"
      - --broker-url=https://pact-broker.api.opg.service.justice.gov.uk/
      - --provider-name=data-lpa-codes
