---
openapi: '3.0.2'
info:
  title: state-${environment}
  version: '1.0'
servers:
  - url: /setup
    description: state path to update local db
paths:
  /dynamodb/create/table:
    post:
      summary: "Setup default table"
      description: "Creates empty table in dynamodb"
      operationId: lpa_codes_mock.create_table_default
      responses:
        201:
          description: "Table created"
  /dynamodb/list:
    get:
      summary: "List tables"
      description: "List tables in dynamodb"
      operationId: lpa_codes_mock.list_tables
      responses:
        200:
          description: "List of tables"
  /dynamodb/clear:
    post:
      summary: "Dynamodb cleardown"
      description: "Removes all tables in dynamodb"
      operationId: lpa_codes_mock.clear_all
      responses:
        201:
          description: "List of tables"
  /dynamodb/table/{table_name}/create:
    post:
      summary: "Setup Bespoke Table"
      description: "Creates empty table in dynamodb given json passed in"
      operationId: lpa_codes_mock.create_table
      parameters:
        - in: path
          name: table_name
          required: true
          description: table name
          schema:
            $ref: '#/components/schemas/table_name'
      responses:
        201:
          description: "Table created"
  /dynamodb/table/{table_name}/delete:
    post:
      summary: "Delete a Table"
      description: "Deletes a given dynamodb table"
      operationId: lpa_codes_mock.delete_table
      parameters:
        - in: path
          name: table_name
          required: true
          description: table name
          schema:
            $ref: '#/components/schemas/table_name'
      responses:
        201:
          description: "Table deleted"
  /dynamodb/table/{table_name}/rows/create:
    post:
      summary: "Create rows"
      description: "Creates rows in given table given json passed in"
      operationId: lpa_codes_mock.create_rows
      parameters:
        - in: path
          name: table_name
          required: true
          description: table name
          schema:
            $ref: '#/components/schemas/table_name'
      responses:
        201:
          description: "Rows created"
  /dynamodb/table/{table_name}/rows/delete:
    post:
      summary: "Delete a row"
      description: "Deletes rows in given table given json passed in"
      operationId: lpa_codes_mock.delete_rows
      parameters:
        - in: path
          name: table_name
          required: true
          description: table name
          schema:
            $ref: '#/components/schemas/table_name'
      responses:
        201:
          description: "Table created"
  /dynamodb/table/{table_name}/rows/get:
    post:
      summary: "Get a row"
      description: "Get a specific row in dynamo table based on key"
      operationId: lpa_codes_mock.get_rows
      parameters:
        - in: path
          name: table_name
          required: true
          description: table name
          schema:
            $ref: '#/components/schemas/table_name'
      responses:
        200:
          description: "Got rows"
  /dynamodb/table/{table_name}/rows/get/all:
    get:
      summary: "Get all rows"
      description: "Gets all rows in a dynamo table"
      operationId: lpa_codes_mock.get_all_rows
      parameters:
        - in: path
          name: table_name
          required: true
          description: table name
          schema:
            $ref: '#/components/schemas/table_name'
      responses:
        200:
          description: "All rows"
  /state:
    post:
      summary: "Update PACT state in dynamodb"
      description: "Endpoint to update the PACT state in dynamodb dependent on what pact verification sends"
      operationId: lpa_codes_mock.update_state
      responses:
        201:
          description: "Row inserted"
components:
  schemas:
    table_name:
      type: string
      example: 'lpa_codes_testing'
