---
version: 2.1

parameters:
  run_pull_request:
    type: boolean
    default: true
  run_commit_to_master:
    type: boolean
    default: true
  run_verify_pact:
    type: boolean
    default: true
  consumerversion:
    type: string
    default: ""
  consumer:
    type: string
    default: ""

workflows:
  pull_request:
    when: << pipeline.parameters.run_pull_request >>
    jobs:
      - build_lambda:
          name: build and artifact
          filters: {branches:{ignore:[master]}}

      - terraform_pre_checks:
          name: terraform preflight checks
          requires: [build and artifact]
          filters: {branches:{ignore:[master]}}

      - terraform_action:
          name: apply branch environment
          requires: [terraform preflight checks]
          tf_command: apply
          filters: {branches:{ignore:[master]}}

      - cleanup:
          name: approve destroy environment
          type: approval
          requires: [apply branch environment]
          filters: {branches:{ignore:[master]}}

      - terraform_action:
          name: destroy branch environment
          requires: [approve destroy environment]
          tf_command: destroy
          destroy_workspace: true
          filters: {branches:{ignore:[master]}}

  commit_to_master:
    when: << pipeline.parameters.run_commit_to_master >>
    jobs:
      - build_lambda:
          name: build and artifact
          filters: {branches:{only:[master]}}

      - terraform_action:
          name: development apply
          requires: [build and artifact]
          tf_command: apply --auto-approve
          tf_workspace: development
          applycheck: true
          filters: {branches:{only:[master]}}

      - terraform_action:
         name: preprod apply
         requires: [development apply]
         tf_command: apply --auto-approve
         tf_workspace: preproduction
         applycheck: true
         filters: {branches:{only:[master]}}

      - approve:
         name: approve release to production
         type: approval
         requires: [preprod apply]
         filters: {branches:{only:[master]}}

      - terraform_action:
          name: integration apply
          requires: [approve release to production]
          tf_command: apply --auto-approve
          tf_workspace: integration
          applycheck: true
          filters: {branches:{only:[master]}}

      - terraform_action:
          name: integration apply
          requires: [approve release to production]
          tf_command: apply --auto-approve
          tf_workspace: integration
          applycheck: true
          filters: {branches:{only:[master]}}
      - terraform_action:
         name: production apply
         requires: [approve release to production]
         tf_command: apply --auto-approve
         tf_workspace: production
         applycheck: true
         filters: {branches:{only:[master]}}
         pact_tag_production: true

  verify_pact:
    when: << pipeline.parameters.run_verify_pact >>
    jobs:
      - pact_verification:
          name: verify the latest pact

orbs:
  lpa-codes:
    executors:
      python_with_tfvars:
        docker:
          - image: circleci/python:3.8.1
        environment:
          TF_CLI_ARGS_plan: -input=false -lock=false
          TF_CLI_ARGS_apply: -input=false -auto-approve
          TF_CLI_ARGS_destroy: -input=false -auto-approve
          TF_CLI_ARGS_init: -input=false -upgrade=true -reconfigure
          TF_VAR_default_role: sirius-ci
          TF_VERSION: 0.12.26
          TF_SHA256SUM: 607bc802b1c6c2a5e62cc48640f38aaa64bef1501b46f0ae4829feb51594b257
      python:
        docker:
          - image: circleci/python:3.8.1
    commands:
      terraform_install:
        steps:
          - run:
              name: Download Terraform
              command: curl -sfSO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          - run:
              name: Add Terraform SHA256SUM
              command: echo "${TF_SHA256SUM} terraform_${TF_VERSION}_linux_amd64.zip" > SHA256SUMS
          - run:
              name: Check Terraform SHA256SUM
              command: sha256sum -c --status SHA256SUMS
          - run:
              name: Install Terraform
              command: sudo unzip terraform_${TF_VERSION}_linux_amd64.zip -d /bin
# PINNING FOR NOW AS MAJOR VERSION BREAKS CODE
#          - run:
#              name: Get latest terraform version
#              command: |
#                export TERRAFORM_LATEST_VERSION=$(curl -X GET -s https://releases.hashicorp.com/terraform/ \
#                | grep "<a href=\"/terraform/" \
#                | awk -F'/' '{print $3}' | head -1)
#                export TERRAFORM_SHA256SUM=$(curl -X GET -s \
#                https://releases.hashicorp.com/terraform/"${TERRAFORM_LATEST_VERSION}"/terraform_"${TERRAFORM_LATEST_VERSION}"_SHA256SUMS \
#                | grep "_linux_amd64.zip" \
#                | head -1 \
#                | awk '{print $1}')
#                echo "export TF_VERSION=${TERRAFORM_LATEST_VERSION}" >> $BASH_ENV
#                echo "export TF_SHA256SUM=${TERRAFORM_SHA256SUM}" >> $BASH_ENV
      aws_cli_install:
        steps:
          - run:
              name: install aws cli
              command: |
                pip3 install awscli --upgrade --user
                aws --version
jobs:
  build_lambda:
    executor: lpa-codes/python
    steps:
      - checkout
      - run:
          name: install all requirements locally
          command: |
            for i in $(ls -d lambda_functions/*/ | awk -F'/' '{print $2}')
            do
              pip3 install -r ./lambda_functions/"${i}"/requirements/dev-requirements.txt
            done
      - run:
          name: run flake8 - python PEP8 linter, complexity checker
          command: |
            flake8 lambda_functions
      - run:
          name: get test coverage (fails below 90%)
          command: |
            python -m pytest --cov=lambda_functions/v1/functions/lpa_codes/app/api/ --cov-fail-under=90
      - run:
          name: run unit tests (with pytest)
          command: |
            python -m pytest
      - run:
          name: install requirements for all lambda layers
          command: |
            for i in $(ls -d lambda_functions/*/ | awk -F'/' '{print $2}' | grep '^v[1-9]\+')
            do
              export LAYER_PATH=lambda_functions/"${i}"/lambda_layers/python/lib/python3.7/site-packages
              pip3 install -r lambda_functions/"${i}"/requirements/requirements.txt --target ./$LAYER_PATH/
            done
      - run:
          name: create artifact for future stages
          command: |
            chmod -R 755 ./lambda_functions
            zip -r9 /tmp/opg-data-lpa-codes.zip .
      - persist_to_workspace:
          root: /tmp
          paths:
            - opg-data-lpa-codes.zip

  terraform_pre_checks:
    executor: lpa-codes/python_with_tfvars
    parameters:
      tf_workspace:
        description: terraform workspace
        type: string
        default: ""
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - lpa-codes/terraform_install
      - run:
          name: unzip artifact
          command: unzip ./opg-data-lpa-codes.zip -d .
      - run:
          name: initialize terraform - environment
          working_directory: ~/project/terraform/environment
          command: terraform init
      - run:
          name: Set BASH_ENV
          command: ~/project/.circleci/set_env.sh >> $BASH_ENV
      - run:
          name: terraform check formatting - environment
          working_directory: ~/project/terraform/environment
          command: terraform fmt -diff -check -recursive
      - run:
          name: validate terraform - environment
          working_directory: ~/project/terraform/environment
          command: terraform validate
      - run:
          name: terraform plan - branch
          working_directory: ~/project/terraform/environment
          command: terraform plan -input=false
      - run:
          name: terraform plan - development
          working_directory: ~/project/terraform/environment
          command: |
            rm -rf .terraform
            export TF_WORKSPACE=development
            terraform init
            terraform plan -input=false
      - run:
          name: terraform plan - integration
          working_directory: ~/project/terraform/environment
          command: |
            rm -rf .terraform
            export TF_WORKSPACE=integration
            terraform init
            terraform plan -input=false
      - run:
          name: terraform plan - preproduction
          working_directory: ~/project/terraform/environment
          command: |
            rm -rf .terraform
            export TF_WORKSPACE=preproduction
            terraform init
            terraform plan -input=false
      - run:
          name: terraform plan - production
          working_directory: ~/project/terraform/environment
          command: |
            rm -rf .terraform
            export TF_WORKSPACE=production
            terraform init
            terraform plan -input=false

  terraform_action:
    executor: lpa-codes/python_with_tfvars
    parameters:
      tf_workspace:
        description: terraform workspace
        type: string
        default: ""
      tf_command:
        description: terraform command
        default: plan
        type: string
      applycheck:
        description: workaround for rest api provider
        type: boolean
        default: false
      destroy_workspace:
        description: whether to destroy the empty workspace
        type: boolean
        default: false
      pact_tag_production:
        description: to tag the production commit
        type: boolean
        default: false
    environment:
      WORKSPACE: << parameters.tf_workspace >>
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - when:
          condition: << parameters.pact_tag_production >>
          steps:
            - lpa-codes/aws_cli_install
      - lpa-codes/terraform_install
      - run:
          name: unzip artifact
          command: unzip ./opg-data-lpa-codes.zip -d .
      - run:
          name: Set BASH_ENV
          command: ~/project/.circleci/set_env.sh >> $BASH_ENV
      - run:
          name: Set Environment variables
          command: |
            eval $(cat $BASH_ENV)
      - run:
          name: initialize terraform - environment
          working_directory: ~/project/terraform/environment
          command: terraform init
      - run:
          name: terraform << parameters.tf_command >> - environment
          working_directory: ~/project/terraform/environment
          command: terraform << parameters.tf_command >>
      # https://github.com/terraform-providers/terraform-provider-aws/issues/5364
      - when:
          condition: << parameters.applycheck >>
          steps:
            - run:
                name: conditionally reapply if gateway policy is missing
                working_directory: ~/project/terraform/environment
                command: |
                  if [ $(terraform output policy | wc -m) -gt 1 ]
                  then echo "policy attached, doing nothing"
                  else terraform << parameters.tf_command >>
                  fi
      - when:
          condition: << parameters.destroy_workspace >>
          steps:
            - run:
                name: destroy the workspace to clear up
                command: |
                  export WORKSPACE_TO_DELETE="${TF_WORKSPACE}"
                  echo "Switching workspace to default so we can remove branch workspace"
                  export TF_WORKSPACE=default
                  terraform workspace delete "${WORKSPACE_TO_DELETE}" || echo "no workspace to remove"
      - when:
          condition: << parameters.pact_tag_production >>
          steps:
            - run:
                name: tag pact commit with v<x>_production
                command: |
                  echo "applying tag on version ${GIT_COMMIT_PROVIDER}"
                  STATUS_CODE=$(curl -I -s -X GET -u "${PACT_BROKER_USER}":"${PACT_BROKER_PASSWORD}" \
                  https://"${PACT_BROKER_BASE_URL}"/pacticipants/"${PACT_PROVIDER}"/versions/"${GIT_COMMIT_PROVIDER}" | grep "HTTP" | awk '{print $2}')

                  if [ "${STATUS_CODE}" -eq "200" ]
                  then
                    STATUS_CODE=$(curl -I -s -X PUT -u "${PACT_BROKER_USER}":"${PACT_BROKER_PASSWORD}" -H "Content-Type: application/json" \
                    https://"${PACT_BROKER_BASE_URL}"/pacticipants/"${PACT_PROVIDER}"/versions/"${GIT_COMMIT_PROVIDER}"/tags/"${API_VERSION}_production" \
                     | grep "HTTP" | awk '{print $2}')
                    echo "Pact tagging completed with status code: ${STATUS_CODE}"
                  else
                    echo "version of provider with git commit ${GIT_COMMIT_PROVIDER}, not found"
                  fi
  pact_verification:
    docker:
      # Primary container image where all the steps run.
      - image: circleci/python:3.8.1
      # Service container image made available to the primary container at `host: localhost`
      - image: amazon/dynamodb-local:latest
        entrypoint: ["java", "-Xmx1G", "-jar", "DynamoDBLocal.jar"]
    working_directory: ~/project
    parameters:
    environment:
      GIT_CONSUMER: << pipeline.parameters.consumer >>
      GIT_COMMIT_CONSUMER: << pipeline.parameters.consumerversion >>
    steps:
      - checkout
      - lpa-codes/aws_cli_install
      - run:
          name: Set BASH_ENV
          command: ~/project/.circleci/set_env.sh >> $BASH_ENV
      - run:
          name: install requirements mock rest api
          command: |
            cd ~/project/lambda_functions/${API_VERSION}/requirements
            pip3 install -r pact-requirements.txt
      - run:
          name: spin up mock rest api
          command: |
            cd ~/project/lambda_functions/"${API_VERSION}"/functions/lpa_codes/app
            export PYTHONPATH="${PYTHONPATH}:/home/circleci/project"
            python3 lpa_codes_mock.py
          background: true
      - run:
          name: check mock rest api started
          command: |
            sleep 3
            if [ `netstat -tulpn | grep 4343 | wc -l` -gt 0 ]
            then
            echo "LPA Codes Rest API Service Started Correctly"
            else
            echo "LPA Codes Rest API Service Not Started"
            fi
      - run:
          name: Set up ready for pact tests
          command: |
            export PACT_VERSION=$(curl -i -s -X GET https://github.com/pact-foundation/pact-ruby-standalone/releases/latest \
            | grep "location:" | awk -F'tag' '{print $2}' | awk -F'/v' '{print $2}' | sed 's/.$//')
            wget https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v${PACT_VERSION}/pact-${PACT_VERSION}-linux-x86_64.tar.gz
            tar xzf pact-${PACT_VERSION}-linux-x86_64.tar.gz
      - run:
          name: Run the create table endpoint
          command: |
            curl -X POST http://127.0.0.1:4343/setup/dynamodb/create/table
      - run:
          name: Set up the data in tables
          command: |
            curl -X POST -d '{"consumer": "sirius", "state": "generated code exists and active"}' \
            -H 'Content-Type: application/json' http://localhost:4343/setup/state
      - run:
          name: verify pact and update github
          command: |
            export SCRIPT_PATH="/home/circleci/project/.circleci"
            if [ "${GIT_COMMIT_CONSUMER}" == "" ]
            then
              printf "\n\nProcess kicked off by commit to lpa-codes\n\n"
              if [ "$TF_WORKSPACE" != "development" ] && [ "$TF_WORKSPACE" != "preproduction" ] && [ "$TF_WORKSPACE" != "production" ]
              then
                printf "\n\nSetting CONSUMER_TRIGGERED to false\n\n"
                export CONSUMER_TRIGGERED=false
                printf "\n\nOn working branch, performing pact verification\n\n"
                "${SCRIPT_PATH}"/pact_verifier.sh
                printf "\n\nChecking if we can deploy with can-i-deploy\n\n"
                "${SCRIPT_PATH}"/check_pact_deployable.sh
              else
                printf "\n\nOn master branch for lpa-codes, no need to perform verification\n\n"
              fi
            elif [ "${GIT_COMMIT_CONSUMER}" != "" ]
            then
              printf "\n\nSetting CONSUMER_TRIGGERED to true\n\n"
              export CONSUMER_TRIGGERED=true
              printf "Process kicked off by commit %b to sirius\n\n" "${GIT_COMMIT_CONSUMER}"
              printf "\n\nChecking if we can deploy with can-i-deploy\n\n"
              "${SCRIPT_PATH}"/check_pact_deployable.sh
            else
              printf "\n\nSomething has gone wrong! Check what GIT_COMMIT_CONSUMER is set to\n\n"
            fi
