FROM python:3.13-slim@sha256:5f55cdf0c5d9dc1a415637a5ccc4a9e18663ad203673173b8cda8f8dcacef689
WORKDIR /var/www/lambda_functions/v1

# Install Python Dependencies
COPY requirements/requirements.txt requirements/requirements.txt
COPY requirements/mock-requirements.txt requirements/mock-requirements.txt
RUN pip install -r ./requirements/requirements.txt
RUN pip install -r ./requirements/mock-requirements.txt

EXPOSE 4343

ENTRYPOINT ["python", "/var/www/lambda_functions/v1/functions/lpa_codes/app/lpa_codes_mock.py"]
