FROM python:3.12-slim@sha256:b03eed4944bc758029e0506ec41acb6a4be6d1b2b875d6e04ac4759db343a370
ARG FUNCTION_DIR="/var/www/lambda_functions/v1"

# Create function directory
RUN mkdir -p ${FUNCTION_DIR}

COPY functions/lpa_codes/app ${FUNCTION_DIR}/functions/lpa_codes/app
COPY tests ${FUNCTION_DIR}/tests

COPY requirements/requirements.txt requirements.txt
COPY requirements/dev-requirements.txt dev-requirements.txt

# Install the runtime interface client
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -r dev-requirements.txt
ENV PYTHONPATH "${PYTHONPATH}:${FUNCTION_DIR}"

WORKDIR /var/www/
# Set the entrypoint for the unit tests
ENTRYPOINT [ "python", "-m", "pytest", "lambda_functions/v1/tests/", "--cov=lambda_functions/v1/functions/lpa_codes/app/api/", "--cov-fail-under=90" ]
