FROM python:3.13-slim@sha256:087a9f3b880e8b2c7688debb9df2a5106e060225ebd18c264d5f1d7a73399db0
ARG FUNCTION_DIR="/var/www/lambda_functions/v1"

# Create function directory
RUN mkdir -p ${FUNCTION_DIR}

COPY functions/lpa_codes/app ${FUNCTION_DIR}/functions/lpa_codes/app
COPY tests ${FUNCTION_DIR}/tests

COPY requirements/requirements.txt requirements.txt
COPY requirements/dev-requirements.txt dev-requirements.txt

# Install the runtime interface client
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -r dev-requirements.txt
ENV PYTHONPATH "${PYTHONPATH}:${FUNCTION_DIR}"

WORKDIR /var/www/
# Set the entrypoint for the unit tests
ENTRYPOINT [ "python", "-m", "pytest", "lambda_functions/v1/tests/", "--cov=lambda_functions/v1/functions/lpa_codes/app/api/", "--cov-fail-under=90" ]
