FROM python:3.14-slim@sha256:4ed33101ee7ec299041cc41dd268dae17031184be94384b1ce7936dc4e5dead3
WORKDIR /var/www/lambda_functions/v1

# Install Python Dependencies
COPY requirements/requirements.txt requirements/requirements.txt
COPY requirements/mock-requirements.txt requirements/mock-requirements.txt
RUN pip install -r ./requirements/requirements.txt
RUN pip install -r ./requirements/mock-requirements.txt

EXPOSE 4343

ENTRYPOINT ["python", "/var/www/lambda_functions/v1/functions/lpa_codes/app/lpa_codes_mock.py"]
