openapi: '3.0.2'
info:
  title: Code Generator
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /healthcheck:
    get:
      responses:
        200:
          description: OK
  /create:
    post:
      summary: "Create a new code"
      description: "Create a new 12 digit alpha-numeric code unique to this LPA and Actor"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lpa:
                  type: string
                  # not sure what 'LPA' refers to here, see ticket IN-71
                actor:
                  type: string
                  # not sure what 'actor' refers to here, see ticket IN-71
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeCreated'
        400:
          description: Generic bad request (generally invalid syntax)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error400'
        401:
          description: Unauthorised (no current user and there should be)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error401'
        403:
          description: Forbidden - The current user is forbidden from accessing this data (in this way)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error403'
        404:
          description: That URL is not a valid route, or the item resource does not exist
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error404'
        413:
          description: Payload too large
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error413'
        415:
          description: Unsupported media type
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error415'
        500:
          description: Something unexpected happened and it is the API"s fault
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error500'
        503:
          description: Service Unavailable - please try again later
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error503'
  /validate:
    post:
      summary: "Validate a code"
      description: "Validate a code"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lpa:
                  type: string
                  # not sure what 'LPA' refers to here, see ticket IN-71
                actor:
                  type: string
                  # not sure what 'actor' refers to here, see ticket IN-71
                code:
                  type: string
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateCode'
        400:
          description: Generic bad request (generally invalid syntax)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error400'
        401:
          description: Unauthorised (no current user and there should be)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error401'
        403:
          description: Forbidden - The current user is forbidden from accessing this data (in this way)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error403'
        404:
          description: That URL is not a valid route, or the item resource does not exist
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error404'
        413:
          description: Payload too large
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error413'
        415:
          description: Unsupported media type
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error415'
        500:
          description: Something unexpected happened and it is the API"s fault
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error500'
        503:
          description: Service Unavailable - please try again later
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error503'
  /revoke:
    post:
      summary: "Revoke a code"
      description: "Revoke a code"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeRevoked'
        400:
          description: Generic bad request (generally invalid syntax)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error400'
        401:
          description: Unauthorised (no current user and there should be)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error401'
        403:
          description: Forbidden - The current user is forbidden from accessing this data (in this way)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error403'
        404:
          description: That URL is not a valid route, or the item resource does not exist
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error404'
        413:
          description: Payload too large
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error413'
        415:
          description: Unsupported media type
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error415'
        500:
          description: Something unexpected happened and it is the API"s fault
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error500'
        503:
          description: Service Unavailable - please try again later
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error503'

components:
  schemas:
    CodeCreated:
      properties:
        code:
          type: string
        status:
          type: string
        id:
          type: string
      required:
        - code
    CodeRevoked:
      properties:
        code:
          type: string
        status:
          type: string
        id:
          type: string
      required:
        - code
    ValidateCode:
      properties:
        code:
          type: string
        status:
          type: string
        id:
          type: string
      required:
        - code
    Error400:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-INVALIDREQUEST"
              title:
                type: string
                example: "Invalid Request"
              detail:
                type: string
                example: "Invalid request, the data is incorrect"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
    Error401:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-UNAUTHORISED"
              title:
                type: string
                example: "User is not authorised"
              detail:
                type: string
                example: "Unauthorised (no current user and there should be)"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
    Error403:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-FORBIDDEN"
              title:
                type: string
                example: "Access Denied"
              detail:
                type: string
                example: "Forbidden - The current user is forbidden from accessing this data (in this way)"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
    Error404:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-NOTFOUND"
              title:
                type: string
                example: "Page not found"
              detail:
                type: string
                example: "That URL is not a valid route, or the item resource does not exist"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
    Error413:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-FILESIZELIMIT"
              title:
                type: string
                example: "Payload too large"
              detail:
                type: string
                example: "Payload too large, try and upload in smaller chunks"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
    Error415:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-MEDIA"
              title:
                type: string
                example: "Unsupported media type"
              detail:
                type: string
                example: "Unsupported media type for this endpoint"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
    Error500:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-SERVERERROR"
              title:
                type: string
                example: "Internal server error"
              detail:
                type: string
                example: "Something unexpected happened internally"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
    Error503:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-UNAVAILABLE"
              title:
                type: string
                example: "Service Unavailable"
              detail:
                type: string
                example: "Service is currently unavailable. Please try again later"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
