name: Generate scan report

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Monday, at 15:40 UTC
    - cron: '40 15 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ministryofjustice/opg-repository-scanner@latest
