permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for docker image"
        required: true
        type: string
      branch_name:
        description: "Branch we are on"
        required: true
        type: string
    secrets:
      SNYK_OPG_ORG_TOKEN:
        required: true

jobs:
  docker_build_scan_push:
    name: Build, Scan and Push Lambdas
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_MANAGEMENT_ECR_ROLE }}
          role-duration-seconds: 900
          role-session-name: OPGLPACodesDockerBuildGithubAction

      - name: Login to ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
        with:
          registries: 311462405659

      - name: Build Container
        id: build_container
        run: docker build --platform linux/amd64 --provenance=false --tag lpa-codes:latest --target production .

      - name: Run SNYK vulnerability scan
        id: snyk_scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@722a5f955424aaba01e9ca43d68390cd4048d6e1 # v4.10.2
        with:
          SNYK_TEST_IMAGE: lpa-codes:latest
          SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
          snyk_test_args: --severity-threshold=high

      - name: Upload SNYK scan results to GitHub Security tab
        id: snyk_upload_sarif
        if: always()
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: "test-results/snyk.sarif"

      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: integrations/lpa-codes-lambda
          BRANCH_NAME: ${{ inputs.branch_name }}
        run: |
          docker tag lpa-codes:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.tag }}
          if [ $BRANCH_NAME == "main" ]; then
            docker tag lpa-codes:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          fi
            echo "skipping push for now..."
            docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
