on:
  workflow_call:
    outputs:
      version_tag:
        description: "Version Tag"
        value: ${{ jobs.create_tags.outputs.version_tag }}
    inputs:
      branch_name:
        type: string
        description: "Current Github branch name"
        required: true
    secrets:
      source_github_token:
          required: true

jobs:
  create_tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install semver
        id: install_semver
        run: sudo npm install -g semver

      - name: Bump version
        id: bump_version
        run: |
          sudo chmod 755 ./scripts/tag.sh
          ./scripts/tag.sh
        env:
          GITHUB_TOKEN: ${{ secrets.source_github_token }}
          INITIAL_VERSION: 0.0.0
          DEFAULT_BUMP: minor
          PRERELEASE_SUFFIX: ${{ inputs.branch_name }}
          RELEASE_BRANCHES: main
          WITH_V: true
          TAG_CONTEXT: branch
    outputs:
      version_tag: ${{ steps.bump_version.outputs.tag }}
