---
permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:

jobs:
  functional_tests:
    name: Run functional tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '^1.25'
          cache-dependency-path: '**/go.sum'

      - name: Run Functional Tests
        id: functional_tests
        run: |
          make test
        env:
          AWS_ACCESS_KEY_ID: testing
          AWS_SECRET_ACCESS_KEY: testing #pragma: allowlist secret
          AWS_SECURITY_TOKEN: testing
          AWS_SESSION_TOKEN: testing
          AWS_DEFAULT_REGION: eu-west-1

