permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none
  
on:
  workflow_call:
    inputs:
      workspace:
        description: 'Workspace to use'
        required: true
        type: string
    secrets:
      github_access_token:
        description: 'Github Token'
        required: true


jobs:
  terraform_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0'

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_DEVELOPMENT_TEST_RUNNER_ROLE }}
          role-duration-seconds: 3600
          role-session-name: OPGLPACodesIntegrationTests

      - name: Install dependencies
        env:
          TF_WORKSPACE: ${{ inputs.workspace }}
        working-directory: scripts/ci_pipeline/load_testing
        run: |
          if [ "${TF_WORKSPACE}" == "development" ]
            then
              echo "Running against development"
              export BRANCH="dev"
            else
              echo "Running against branch environment"
              export BRANCH="${TF_WORKSPACE}.dev"
            fi
            go run load_testing.go
