permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for docker image"
        required: true
        type: string
      branch_name:
        description: "Branch we are on"
        required: true
        type: string
    secrets:
      aws_access_key_id_actions:
        required: true
      aws_secret_access_key_actions:
        required: true
      SNYK_OPG_ORG_TOKEN:
        required: true

jobs:
  docker_build_scan_push:
    name: Build, Scan and Push Lambdas
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id_actions }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key_actions }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::311462405659:role/integrations-ci
          role-duration-seconds: 900
          role-session-name: OPGLPACodesGithubAction

      - name: Login to ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registries: 311462405659

      - name: Build Container
        id: build_container
        run: docker build --platform linux/amd64 --provenance=false --tag lpa-codes:latest --target production .

      - name: Run SNYK vulnerability scan
        id: snyk_scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@8dea82fc8b8e7ffca431f0fb83848d523147ccd8 # v4.5.0
        continue-on-error: true
        with:
          SNYK_TEST_IMAGE: lpa-codes:latest
          SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
          sarif_filename: snyk-results.sarif
          snyk_test_args: "--exclude-base-image-vulns"

      - name: Upload SNYK scan results to GitHub Security tab
        id: snyk_upload_sarif
        uses: github/codeql-action/upload-sarif@9e907b5e64f6b83e7804b09294d44122997950d6 # v4.32.3
        with:
          sarif_file: "snyk-results.sarif"

      - name: Fail build on High/Critical vulnerabilities
        id: snyk_scan_critical
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
        with:
          image: lpa-codes:latest
          severity-threshold: high
          skip-setup: true

      - name: Install AWS Cli
        uses: unfor19/install-aws-cli-action@f5b46b7f32cf5e7ebd652656c5036bf83dd1e60c # 1.0.8

      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: integrations/lpa-codes-lambda
          BRANCH_NAME: ${{ inputs.branch_name }}
        run: |
          docker tag lpa-codes:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.tag }}
          if [ $BRANCH_NAME == "main" ]; then
            docker tag lpa-codes:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          fi
            echo "skipping push for now..."
            docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
