permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@v4.1.3

      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: '3.11'

      - name: Install requirements
        id: requirements
        run: |
          pip install -r ./lambda_functions/v1/requirements/requirements.txt
          pip install -r ./lambda_functions/v1/requirements/dev-requirements.txt

      - name: Run Unit Tests
        id: unit_tests
        run: |
          python -m pytest lambda_functions/v1/ --cov=lambda_functions/v1/functions/lpa_codes/app/api/ --cov-fail-under=90
