name: '[Terraform] Validate terraform'

defaults:
  run:
    shell: bash

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    inputs:
      oidc_role:
        description: 'The OIDC role to assume for AWS access'
        required: true
        type: string
      workspace:
        description: 'Terraform workspace'
        required: true
        type: string
    secrets:
      github_access_token:
        description: 'Github Token'
        required: true
      ssh_private_key_allow_list_repository:
        required: true
jobs:
  lint-terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - folder: 'environment'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 'Set terraform version'
        id: set-terraform-version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@b8868247a908f74fafe1905701391580575a6d35 # v4.3.10
        with:
          terraform_directory: ./terraform/${{ matrix.folder}}

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.set-terraform-version.outputs.version }}

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_role }}
          role-duration-seconds: 3600
          role-session-name: OPGLPACodesGithubAction

      - name: terraform fmt ${{ matrix.folder }} check
        run: terraform fmt -check -recursive
        working-directory: ./terraform/${{ matrix.folder }}

      - id: deploy-key
        uses: ministryofjustice/opg-github-actions/actions/github-deploy-key@a2907c7c7be94301c965ace76a2cfa407ad6fc88 # v4.6.0
        with:
          deploy_key: ${{ secrets.ssh_private_key_allow_list_repository }}

      - name: terraform validate ${{ inputs.workspace }}
        env:
          TF_WORKSPACE: default
        run: |
          terraform --version
          terraform init
          echo $TF_WORKSPACE
          terraform validate
        working-directory: ./terraform/${{ matrix.folder }}
