name: "[Workflow] Pull Request Path"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

on:
  pull_request:
    branches:
      - main

jobs:
  pr_label:
    runs-on: ubuntu-latest
    name: Label PR
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          configuration-path: ".github/labeller.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  branch_name:
    runs-on: ubuntu-latest
    name: Extract branch name
    outputs:
      raw_branch: ${{ steps.extract_branch.outputs.branch_raw }}
      formatted_branch: ${{ steps.extract_branch.outputs.branch_formatted }}
    steps:
      - name: Extract branch
        shell: bash
        run: |
          echo "branch_raw=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}})" >> $GITHUB_OUTPUT
          echo "branch_formatted=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}} | tr -cd '[:alnum:]' | tr '[:upper:]' '[:lower:]' | cut -c1-10)" >> $GITHUB_OUTPUT
        id: extract_branch

  create_tags:
    name: Create Tags
    needs: ["branch_name"]
    uses: ./.github/workflows/sub-task-tags.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      source_github_token: ${{ secrets.GITHUB_TOKEN }}

  terraform_lint:
    name: Lint terraform code
    uses: ./.github/workflows/sub-task-lint.yml
    needs: ["branch_name"]
    with:
      oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
      workspace: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      ssh_private_key_allow_list_repository: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  functional_tests:
    name: Functional tests
    needs: ["create_tags", "branch_name"]
    uses: ./.github/workflows/sub-task-functional-tests.yml

  docker_build_scan_push:
    name: Build, Scan and Push
    needs: ["create_tags", "branch_name"]
    uses: ./.github/workflows/sub-task-docker-build.yml
    with:
      tag: ${{ needs.create_tags.outputs.version_tag }}
      branch_name: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      SNYK_OPG_ORG_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}

  build_pr_environment:
    name: Build PR Environment
    needs:
      [
        "docker_build_scan_push",
        "terraform_lint",
        "create_tags",
        "branch_name",
        "functional_tests",
      ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      apply: true
      terraform_path: "terraform/environment"
      default_role: ${{ vars.DEVELOPMENT_ROLE }}
      oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      image_tag: ${{ needs.create_tags.outputs.version_tag }}
      workspace: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      ssh_private_key_allow_list_repository: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  integration_tests:
    name: Integration tests against branch environment
    needs: ["build_pr_environment", "create_tags", "branch_name"]
    uses: ./.github/workflows/sub-task-integration-tests.yml
    with:
      workspace: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
  
  plan-environments:
    strategy:
      matrix:
        include:
          - workspace: development
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.DEVELOPMENT_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
          - workspace: preproduction
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.PREPRODUCTION_PULL_REQUEST_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
          - workspace: production
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.PRODUCTION_PULL_REQUEST_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
    name: "TF Plan Environment: ${{ matrix.workspace }}"
    needs: 
      [
        "docker_build_scan_push",
        "terraform_lint",
        "create_tags",
        "branch_name",
        "functional_tests",
      ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      apply: false
      terraform_path: "terraform/environment"
      workspace: ${{ matrix.workspace }}
      oidc_role: ${{ matrix.oidc_role }}
      default_role: ${{ matrix.default_role }}
      management_role: ${{ matrix.management_role }}
      image_tag: ${{ needs.create_tags.outputs.version_tag }}
    secrets:
      ssh_private_key_allow_list_repository: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  workflow_complete:
    name: Workflow Complete
    runs-on: ubuntu-latest
    needs: ["integration_tests", "plan-environments"]
    steps:
      - name: Completion message
        run: echo "Workflow Complete"
